// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>
[id='get-started-radanalyticsio']
= Get Started with radanalytics.io
:page-layout: markdown
:page-title: Get Started
:page-menu_entry: Get Started

== Overview

The radanalytics.io projects are all focused on increasing your ability to
design, deploy, and maintain insightful data-driven applications. The
foundation of this effort are infrastructure projects which simplify the
process of deploying and managing data processing frameworks.

This introduction will help you learn about the primary radanalytics.io
projects, how to install them, and how to utilize them with your own
applications.

== Which projects should you start with?

Although the link:/projects[projects] page contains all the collected efforts of
the radanalytics.io community, there are several applications which deserve to
be highlighted as they are key to beginning your journey here.

=== Oshinko

The Oshinko project covers several individual applications which all focus on
the goal of deploying and managing https://spark.apache.org[Apache Spark]
clusters on https://www.openshift.com[Red Hat OpenShift] and
https://www.openshift.org[OpenShift Origin].

With the Oshinko family of applications you can create, scale, and destroy
Apache Spark clusters. These clusters can then be used by your applications
within an OpenShift project by providing a simple connection URL to the
cluster. There are multiple paths to achieving this: browser based graphical
interface, command line tool, and a RESTful server.

To begin your exploration, we recommend starting with the
https://github.com/radanalyticsio/oshinko-webui[oshinko-webui] application.
The oshinko-webui is a self-contained deployment of the Oshinko technologies.
An OpenShift user can deploy the oshinko-webui container into their project
and then access the server with a web browser. Through the browser interface
you will be able to manage Apache Spark clusters within your project.

Another important part of Oshinko to highlight is the
https://github.com/radanalyticsio/oshinko-s2i[oshinko-s2i] repository and
associated images which implement the
https://docs.openshift.org/latest/architecture/core_concepts/builds_and_image_streams.html#source-build[source-to-image]
workflow for Apache Spark based applications. These images enable
you to create full applications that can be built, deployed and upgraded
directly from a source repository.

.Additional resources

* link:/howdoi/install-radanalyticsio[How do I install radanalytics.io?]

* link:/howdoi/launch-oshinko-webui-console[How do I launch the Oshinko web interface from the OpenShift console?]

* link:/howdoi/launch-oshinko-webui-cli[How do I launch the Oshinko web interface from the command line?]

* link:my-first-radanalytics-app.html[SparkPi: an introduction to applications using Apache Spark with radanalytics.io]
