= Building Apache Spark Application Pipelines for the Kubernetes Ecosystem
:page-presentor: Michael McCune
:page-date: 2016-12-20
:page-media-url: https://feathercast.apache.org/2016/12/20/apache-big-data-seville-2016-building-apache-spark-application-pipelines-for-the-kubernetes-ecosystem-michael-mccune/
:page-slides-url: https://github.com/elmiko/slidedecks/tree/2016/abd-eu-spark-on-kube

Apache Spark based applications are often comprised of many separate, interconnected components that are a good match for an orchestrated containerized platform like Kubernetes. But with the increased flexibility afforded by these technologies comes a new set challenges for building rich data-centric applications.

In this presentation we will discuss techniques for building multi-component Apache Spark based applications that can be easily deployed and managed on a Kubernetes infrastructure. Building on experiences learned while developing and deploying cloud native applications on an OpenShift platform, we will explore common issues that arise during the engineering process and demonstrate workflows for easing the maintenance factors associated with complex installations.
