= Building My Own Little World with Open Data
:page-presentor: Steven Pousty
:page-date: 2017-01-17
:page-media-url: https://www.youtube.com/watch?v=Wm6JS3ATa1E
:page-slides-url: https://docs.google.com/presentation/d/1waBLFwTAIwteChQb1gI2gqNlYz-ubavRmfnjJG3DToQ/edit#slide=id.p
:page-venue: linux.conf.au
:page-city: Hobart, Australia

Everybody cares about the place (they live, they grew up in, they had a great vacation, in the news….). With the rise of open data, big data tooling, and new visualisation technology, we can actually now build applications that give people new ways to explore beyond “where is the closest Starbucks”. I have collected Open Data from my home town (Santa Cruz, CA) and compiled it into the beginnings of a visualization and analysis platform. The goal of this talk is to show the process of collecting open data from disparate sources, some of the caveats on being able to put them together, general lessons learned, and some fun visualizations. I want to move past thinking about sources for open data and moving on to tools and lessons so you can get cracking! I want to show how we can enable people to gather open data and turn it to open knowledge. Data sources will be from Government (e.g. United States Geologic Survey) and Non-Government sources (e.g Audubon Society eBird Data) while some of the tools covered will be Apache Spark, PostGIS, Leaflet, and various others.
