= Fire in the Sky:  An Introduction to Monitoring Apache Spark in the Cloud
:page-presentor: Michael McCune
:page-date: 2017-10-26
:page-media-url: https://youtu.be/S-1qbcGYPL0
:page-slides-url: https://www.slideshare.net/SparkSummit/fire-in-the-sky-an-introduction-to-monitoring-apache-spark-in-the-cloud-with-michael-mccune
:page-venue: Spark Summit EU
:page-city: Dublin, Ireland

Writing intelligent cloud native applications is hard enough when things go well, but what happens when there are performance and debugging issues that arise during production? Inspecting the logs is a good start, but what if the logs don’t show the whole picture? Now you have to go deeper, examining the live performance metrics that are generated by Spark, or even deploying specialized microservices to monitor and act upon that data. Spark provides several built-in sinks for exposing metrics data about the internal state of its executors and drivers, but getting at that information when your cluster is in the cloud can be a time consuming and arduous process. In this presentation, Michael McCune will walk through the options available for gaining access to the metrics data even when a Spark cluster lives in a cloud native containerized environment. Attendees will see demonstrations of techniques that will help them to integrate a full-fledged metrics story into their deployments. Michael will also discuss the pain points and challenges around publishing this data outside of the cloud and explain how to overcome them. In this talk you will learn about: Deploying metrics sinks as microservices, Common configuration options, and Accessing metrics data through a variety of mechanisms.