= From Research to Production: What they didn’t teach you in Grad School
:page-presentor: Sophie Watson
:page-date: 2018-06-11
:page-media-url: https://youtu.be/s3WbEfoxRjs
:page-venue: Berlin Buzzwords
:page-city: Berlin, Germany

Academic researchers find novel solutions to thorny problems in idealized environments.  A research background is excellent preparation for advancing the state of the art, but newly-minted professional data scientists can find themselves in industry with an arsenal of problem-solving techniques that are not as potent as they seemed in graduate school:  data sets are larger and messier, solutions are judged by their outcomes rather than by their novelty, and products, unlike publications, require ongoing maintenance and support.

This talk will draw on the speaker’s experience bringing a mathematics research background to a team in industry.  We will show both the challenges that data scientists face when entering industry from academia and the unique skills that they bring from their research background.  We shall frame the discussion with a running example of cutting-edge statistical research embodied in an imperfect implementation. We’ll demonstrate iterative refinements to our implementation, showing how to take a research prototype to production code, with particular attention to real-world pitfalls that might not appear in a researcher’s daily work.  Finally, we’ll show how trained researchers can turn their background into a superpower for applied teams in industry.

Early-career attendees who are considering joining industry from academia will learn how to navigate the challenges they’ll face on a mixed team and how to best use their gifts and skills in a new environment. Established practitioners will learn how to support, engage, and nurture their colleagues who are transitioning from academia.  Everyone will learn how to adapt implementations and ideas from the research world for production applications.
