= How do I choose my own Apache Spark distribution?
:page-layout: howdoi
:page-menu_entry: How do I?

When you install radanalytics.io, your project is set up to use a pre-determined distribution of Apache Spark. You can choose your own Apache Spark distribution with a few additional steps:

.Prerequisites

. Follow the instructions under link:/howdoi/install-radanalyticsio[How do I install radanalytics.io?]

. Choose an Apache Spark binary tarball. The tarball may be a local file or a url. Any binary distribution should work as long as the tarball has this basic structure:

* a top-level directory we'll call TOP
* binaries under TOP/bin
* jar files under TOP/jars
* configuration files under TOP/conf

. Optionally download an md5 file for the tarball. If an md5 file is used, both the tarball and the md5 file *must be* put in a subdirectory and that subdirectory specified as the argument to the `build` command below. Additionally, the md5 file should be the name of the tarball with `.md5` appended.

.Procedure

. Get the `rad-image` script

.. The script is available from link:/assets/tools/rad-image[this link], or download it in your shell using curl:

    curl -o rad-image https://radanalytics.io/assets/tools/rad-image

.. Make sure that it's executable:

    chmod +x rad-image

.. By the way, you can access help for `rad-image` like this:

    ./rad-image -h

. Build images using the Spark distribution you've selected. This will create new `complete` tags on the radanaltyics.io image streams in your current OpenShift project. Note that the value for the Spark distribution may be a file, url or subdirectory. Here's an example using a url

    ./rad-image build https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz

.Using Custom Image tags

To build images with a tag other than `complete`, specify the `-t TAG` option on the build command

    ./rad-image build -t 2.3.0 spark-2.3.0-bin-hadoop2.7.tgz

You can switch radanalytics.io components to use the new tag like this

    ./rad-image use 2.3.0

and you can switch back to using the default tag like this

    ./rad-image use -d

.Additional resources

* link:/howdoi/install-radanalyticsio[How do I install radanalytics.io?]

* link:/howdoi/validate-radanalytics-install[How do I validate my radanalytics.io installation?]

* link:/howdoi/launch-oshinko-webui-cli[How do I launch the Oshinko web interface from the command line?]

* link:/howdoi/install-oshinko-cli[How do I install the Oshinko command line interface tool?]
